### ISSUE TITLE
[BUG] Bot choosing texture by itself in choice embed in specific circumstances

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/Discord-Bot#139]
This only happens on specific textures, for example the black_candle. (/texture 16 black_candle)
The choice embed shows 2 results and after adding both reactions, it instantly chooses the first one without any user interaction. So far this hasn't happened on any other texture.

From looking at the code I have no idea how this can happen, and even just on specific textures. I'm really clueless.

**Comment by TheRolfFR** [comment]
it happened to me that was the ChoiceEmbed bug i wrote in the todo, but i'll check it out. Do you have a texture name example where it happens?

**Comment by RobertRR11** [comment]
Like already said, so far it only happened on the "black_candle" texture.

**Comment by TheRolfFR** [comment]
So I made little pieces of code with https://github.com/Compliance-Resource-Pack/Discord-Bot/commit/1eceee4114089be408cd13836a46e5efe55a0f95 and possibly https://github.com/Compliance-Resource-Pack/Discord-Bot/commit/76d5370df0dfe5fb152591ce82e17155334b9ca7 and **I** didn't experienced this problem since. Did **you** have it ?

If you are all okay, we could maybe close this issue.

**Comment by RobertRR11** [comment]
This issue was already fixed a long time ago, I don't know why this isn't closed yet
